apiVersion: v1
kind: Secret
metadata:
  name: clouddeploy-secret
  namespace: clouddeploy
  labels:
    app.kubernetes.io/name: clouddeploy
type: Opaque
stringData:
  POSTGRES_USER: "clouddeploy"
  POSTGRES_PASSWORD: "clouddeploy_secret"
  POSTGRES_DB: "clouddeploy_db"
  DATABASE_URL: "postgresql://clouddeploy:clouddeploy_secret@postgres-service:5432/clouddeploy_db?schema=public"
  JWT_SECRET: "clouddeploy_super_secure_jwt_secret_key_2026_production_style"
